import type { ProfileConfig, ProfileKey } from "./types";

export const PROFILES: Record<ProfileKey, ProfileConfig> = {
  "Defence / Security": {
    thresholdBias: 0,
    minAreaScale: 0.85,
    maxDetections: 8,
    structuralWeight: 1.35,
    spectralWeight: 0.80,
    compactnessWeight: 1.45,
    areaWeight: 0.85,
    edgeWeight: 1.40,
    label: "activity / structural review zone",
    summary: "Prioritises compact activity, object-like, structural, and infrastructure changes.",
    color: "#fb4765",
  },
  "Urban development": {
    thresholdBias: -3,
    minAreaScale: 1.10,
    maxDetections: 10,
    structuralWeight: 1.55,
    spectralWeight: 0.85,
    compactnessWeight: 0.90,
    areaWeight: 1.25,
    edgeWeight: 1.25,
    label: "built-up / infrastructure change zone",
    summary: "Prioritises new construction, roads, dense built-up growth, and large structural shifts.",
    color: "#38bdf8",
  },
  "Environmental monitoring": {
    thresholdBias: -6,
    minAreaScale: 1.25,
    maxDetections: 12,
    structuralWeight: 0.75,
    spectralWeight: 1.60,
    compactnessWeight: 0.55,
    areaWeight: 1.35,
    edgeWeight: 0.70,
    label: "land-cover change zone",
    summary: "Prioritises land-cover, vegetation, water, soil, and broad spectral changes.",
    color: "#34d399",
  },
  "Disaster assessment": {
    thresholdBias: -8,
    minAreaScale: 1.00,
    maxDetections: 14,
    structuralWeight: 1.00,
    spectralWeight: 1.35,
    compactnessWeight: 0.70,
    areaWeight: 1.45,
    edgeWeight: 0.95,
    label: "damage / disturbance review zone",
    summary: "Prioritises large disturbance areas, damaged structures, flood/fire scars, and debris-like changes.",
    color: "#f59e0b",
  },
  "Agriculture / vegetation": {
    thresholdBias: -5,
    minAreaScale: 1.30,
    maxDetections: 12,
    structuralWeight: 0.60,
    spectralWeight: 1.75,
    compactnessWeight: 0.45,
    areaWeight: 1.20,
    edgeWeight: 0.65,
    label: "vegetation / crop condition change",
    summary: "Prioritises vegetation loss, crop-condition change, exposed soil, and field-level spectral shifts.",
    color: "#86efac",
  },
  "Water-body change": {
    thresholdBias: -7,
    minAreaScale: 1.15,
    maxDetections: 10,
    structuralWeight: 0.65,
    spectralWeight: 1.85,
    compactnessWeight: 0.50,
    areaWeight: 1.35,
    edgeWeight: 0.80,
    label: "water boundary / surface change",
    summary: "Prioritises shoreline movement, flood expansion, reservoir shrinkage, and water-surface changes.",
    color: "#22d3ee",
  },
};

export const PROFILE_KEYS = Object.keys(PROFILES) as ProfileKey[];
